//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSConecFM.WSLayoutFacturacionModerna {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://t1demo.facturacionmoderna.com/timbrado/soap", ConfigurationName="WSLayoutFacturacionModerna.Timbrado_ManagerPort")]
    [System.Xml.Serialization.XmlInclude(typeof(WSConecFM.requestTimbrarCFDI))]
    public interface Timbrado_ManagerPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t1demo.facturacionmoderna.com/timbrado/soap#requestTimbrarCFDI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object requestTimbrarCFDI(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t1demo.facturacionmoderna.com/timbrado/soap#requestTimbrarCFDI", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> requestTimbrarCFDIAsync(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t1demo.facturacionmoderna.com/timbrado/soap#requestCancelarCFDI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object requestCancelarCFDI(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t1demo.facturacionmoderna.com/timbrado/soap#requestCancelarCFDI", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> requestCancelarCFDIAsync(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t1demo.facturacionmoderna.com/timbrado/soap#activarCancelacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object activarCancelacion(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t1demo.facturacionmoderna.com/timbrado/soap#activarCancelacion", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> activarCancelacionAsync(object request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Timbrado_ManagerPortChannel : WSConecFM.WSLayoutFacturacionModerna.Timbrado_ManagerPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Xml.Serialization.XmlInclude(typeof(WSConecFM.requestTimbrarCFDI))]
    public partial class Timbrado_ManagerPortClient : System.ServiceModel.ClientBase<WSConecFM.WSLayoutFacturacionModerna.Timbrado_ManagerPort>, WSConecFM.WSLayoutFacturacionModerna.Timbrado_ManagerPort {
        
        public Timbrado_ManagerPortClient() {
        
        }
        
        public Timbrado_ManagerPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Timbrado_ManagerPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Timbrado_ManagerPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Timbrado_ManagerPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object requestTimbrarCFDI(object request) {
            return base.Channel.requestTimbrarCFDI(request);
        }
        
        public System.Threading.Tasks.Task<object> requestTimbrarCFDIAsync(object request) {
            return base.Channel.requestTimbrarCFDIAsync(request);
        }
        
        public object requestCancelarCFDI(object request) {
            return base.Channel.requestCancelarCFDI(request);
        }
        
        public System.Threading.Tasks.Task<object> requestCancelarCFDIAsync(object request) {
            return base.Channel.requestCancelarCFDIAsync(request);
        }
        
        public object activarCancelacion(object request) {
            return base.Channel.activarCancelacion(request);
        }
        
        public System.Threading.Tasks.Task<object> activarCancelacionAsync(object request) {
            return base.Channel.activarCancelacionAsync(request);
        }
    }
}
